name: terraform plan
on: 
  push:
    paths:
      - '01/**'
      - '.github/workflows/*.yml'
  workflow_dispatch:

    inputs:
    working_dir:
      type: string
      required: false
      default: '01'

permissions:
  id-token: write
  contents: read

jobs:
  trraform-init:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Config aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init
        run: terraform -chdir=${{ inputs.working_dir }} init

      - name: Plan
        run: terraform -chdir=${{ inputs.working_dir }} plan -out=tfplan

      - name: Apply
        run: terraform -chdir=${{ inputs.working_dir }} apply -auto-approve tfplan
